name: Package

on:
  workflow_call:
    inputs:
      version_number:
        type: string
        default: 0.0.0
        description: Version number to use for the build (e.g. `1.0.0`).
      enable_ui_access:
        type: boolean
        default: false
        description: (Windows only) Enable UIAccess in the application manifest.
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        default: 0.0.0
        description: Version number to use for the build (e.g. `1.0.0`).
      enable_ui_access:
        type: boolean
        default: false
        description: (Windows only) Enable UIAccess in the application manifest.

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      enable_ui_access: ${{ inputs.enable_ui_access }}
      version_number: ${{ inputs.version_number }}

  package-windows:
    needs: build
    runs-on: windows-latest
    env:
      VERSION: ${{ inputs.version_number }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Download build artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e0059719ce7373ae42 # v4.1.8
        with:
          pattern: build-*
          merge-multiple: true

      - name: Install WiX and its extensions
        run: |
          dotnet tool install --global wix --version 5.0.0
          wix extension add WixToolset.UI.wixext/5 WixToolset.Util.wixext/5 WixToolset.BootstrapperApplications.wixext/5

      - name: Install AzureSignTool
        run: |
          dotnet tool install --global AzureSignTool --version 5.0.0

      - name: Run packaging script
        env:
          AZ_VAULT_URL: ${{ secrets.AZ_VAULT_URL }}
          AZ_CERT_NAME: ${{ secrets.AZ_CERT_NAME }}
          AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          RFC3161_TIMESTAMP_URL: ${{ vars.RFC3161_TIMESTAMP_URL }}
        run: |
          $enableUiAccess = [System.Convert]::ToBoolean('${{ inputs.enable_ui_access }}')
          ./resources/scripts/package.ps1 -VersionNumber $env:VERSION -EnableUiAccess:$enableUiAccess

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: package-windows
          if-no-files-found: error
          path: |
            out/installer-*
            out/glazewm-*.zip
            out/x64/*.exe
            out/arm64/*.exe
